spring:
  datasource:
    druid:
      url: jdbc:mysql://rm-7xv9h5685p98j9642mo.mysql.rds.aliyuncs.com:3306/wiki
      username: wiki
      password: ambitionZCL0
      driver-class-name: com.mysql.cj.jdbc.Driver



druid:
  aop-patterns: edu.scnu.admin.*
  filters: stat, wall, slf4j # 底层开启功能，stat（sql监控），wall（防火墙）
  #监控页的配置
  stat-view-servlet:
    enabled: true
    login-password: admin
    login-username: admin
    reset-enable: false

  #      web监控配置
  web-stat-filter:
    enabled: true
    exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
    url-pattern: /*

  filter: # 对上面filters里面的stat的详细配置
    stat:
      slow-sql-millis: 1000
      log-slow-sql: true
      enabled: true
    wall: # 对上面filters里面的 wall 的详细配置
      enabled: true
      config:
      drop-table-allow: false
mybatis:
  mapper-locations:   classpath:mapper/*.xml
  type-aliases-package:  "edu.scnu.wiki.pojo"
  config-location:  classpath:mybatis-config.xml